- name: get config
  arista.eos.eos_command:
    commands:
      - show run | json

  register: results

# - name: date info
#   set_fact:
#     date_stamp: "{{ lookup('pipe', 'date +%Y-%m-%d_%H-%M') }}"

- name: create folder
  file:
    path: "./reports/{{ phase }}"
    state: directory
    mode: '0755'

- name: export_report
  copy:
    content: "{{ results.stdout[0] | to_nice_json }}"
    dest: "./reports/{{ phase }}/{{ inventory_hostname }}.json"